token:
  expiration_time: 864000
  secret: '{cipher}AQAjIn4hZOGCH0IhxL3r09GVg56Ta3YoeJO/omw7xQF211TzeitDMEuYJgGqEXgFlYneDES+cAV32ioRcCLARzgWweE6Bs0lXob87vlLLBxa8wI0DTMrIh1+5KKsTrmNO0E9YcDLxsf61pH4l8mrucqBAVbjAMK1hPW7H+WKsho/CYSvs9HYn0l8Csvr4pUdyG/vhQhEpNpScbkIjCAMaL55T3puP+8PcWLemK21cIzO2aC6yM0nLDyh6fsMmaDON6W0adZ/Fz972EUAz2Aw9NkcrkW3Nuu1ia7GXjjkRVdO4AdX3TicLZA60Cgowa+fvm/3Al5ARfMtQ1fgaD/xUx84BvYJ5038SsHMzRPmKfWVXsp/GZXgcKC92sqzpvnPO2lf2hcmPXe6kmqZLXxDBJrf'

gateway:
  ip: 192.168.219.102

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost:9092/~/testdb'
    # '{cipher}'는 해당 값이 암호화되었다는 뜻이다. 원래값 sa
    username: '{cipher}AQCB6SvrSHa1sNqH+ZMgXuxxpjbiFH8Ya5E0uK1Cah6kJFYies4TmMgqGFJIA5QOMESWLns36GZ/DM8lAW2q/Dxc4MlFNWvFS7FRm7mXCcgIYkb8irSuAh23J9jkWkzCbbyiJ3AR9McIymJr8iz7iVpZXvROA5Dy0/CDjSbH8qR1SEqIetrBhoin3/fStCAZtkYbCrXuIBy8Rw85IKT59t/XbqPYy3sX1ogW3JVee06X6XCVfVY3L6ypB/vkE9biEKFGpjjAyMr49D5EGzVTGh7Xl3oKutIcjv9h36YJuwr4KLQVZ5BtzYCHekWOxCR6yXjWV3YiYTCEJ6IGGpITX36oW8N/nXECoFTEGo/2AFAd7Pgjw2px8zaGahT+qfN9ShQ='
    password:
